config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors, controllers: {
    sessions: 'visitors/sessions',
    registrations: 'visitors/registrations',
    passwords: 'visitors/passwords'
  }
  devise_for :users

  resources :offers, only: [:index] do
    member do
      get :select, :delete
    end
  end

  namespace :owner do
    resources :offers, only: %i[new create edit update destroy index]
  end

  root to: 'home#index'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :visitor, optional: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_visitor!

  def index
    @offers = Offer.where(visitor_id: [nil, current_visitor.id])
  end

  def select
    @offer = Offer.find_by_id(params[:id])

    if @offer&.update(visitor_id: current_visitor.id)
      flash[:message] = 'Offer selected successfully.'
    else
      flash[:message] = 'Offer could not be selected.'
    end

    redirect_to offers_path
  end

  def delete
    @offer = Offer.find_by_id(params[:id])

    if @offer&.update(visitor_id: nil)
      flash[:message] = 'Offer successfully deleted.'
    else
      flash[:message] = 'Offer could not be deleted.'
    end

    redirect_to offers_path
  end
end

app/controllers/owner/offers_controller.rb
class Owner::OffersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_offer, only: %i[edit update destroy]

  def index
    @offers = Offer.all
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = current_user.offers.build(offer_params)

    if @offer.save
      flash[:message] = 'Offer successfully created.'
      redirect_to owner_offers_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @offer.update(offer_params)
      flash[:message] = 'Offer successfully updated.'
      redirect_to owner_offers_path
    else
      render :edit
    end
  end

  def destroy
    if @offer.destroy
      flash[:message] = 'Offer successfully deleted.'
      redirect_to owner_offers_path
    else
      redirect_to owner_offer_path(@offer)
    end
  end

  private

  # def authenticate_owner
  #   redirect_to root_path unless current_user.is_owner
  # end

  def set_offer
    @offer = Offer.find params[:id]
  end

  def offer_params
    params.require(:offer).permit(:starts, :ends, :days, :capacity, :parking_price, :discount)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/owner/offers/_form.html.erb
<div class='card shadow-lg rounded p-4 border-0'>
  <%= form_for @offer, url: { action: action, method: method }, html: { class: "form-block" }  do |f| %>
    <div class="form-group">
      <%= f.label :starts, class: 'font-weight-bold' %>
      <%= f.date_field :starts, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :ends, class: 'font-weight-bold' %>
      <%= f.date_field :ends, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :days, class: 'font-weight-bold' %>
      <%= f.number_field :days, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :capacity, class: 'font-weight-bold' %>
      <%= f.number_field :capacity, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :parking_price, class: 'font-weight-bold' %>
      <%= f.number_field :parking_price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :discount, class: 'font-weight-bold' %>
      <%= f.number_field :discount, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/owner/offers/edit.html.erb
<div class="container pt-4 pb-4">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Owner</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="<%= owner_offers_path %>">Offers</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="#"></a>Edit Offer</li>
    </ol>
  </nav>

  <%= render "form", url: owner_offer_path, action: 'update' , method: :put %>
</div>

app/views/owner/offers/index.html.erb
<div class="container pt-4 pb-4">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active"><a href="#">Owner</a></li>
      <li class="breadcrumb-item active" aria-current="page">Offers</li>
      <li class="breadcrumb-item active" aria-current="page"><a href="<%= new_owner_offer_path %>">Create Offer</a></li>
    </ol>
  </nav>

  <%= render "shared/flash" %>

  <div class="card shadow-lg">
    <div class="card-body p-0">
      <table class="table">
        <thead class="thead-dark">
          <tr class='text-center'>
            <th scope="col">ID</th>
            <th scope="col">Starts</th>
            <th scope="col">Ends</th>
            <th scope="col">Duration</th>
            <th scope="col">Capacity</th>
            <th scope="col">Parking Price</th>
            <th scope="col">Discount</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>

        <% @offers.each do |offer| %>
          <tr class='text-center'>
            <th scope="row"><%= offer.id %></th>
            <td><%= offer.starts %></td>
            <td><%= offer.ends %></td>
            <td><%= offer.days %></td>
            <td><%= offer.capacity %></td>
            <td><%= offer.parking_price %></td>
            <td><%= offer.discount %></td>
            <td><%= link_to "Edit", edit_owner_offer_path(offer) %></td>
            <td><%= link_to "Delete", owner_offer_path(offer), method: :delete, class: 'delete-offer' %></td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/owner/offers/new.html.erb
<div class="container pt-4 pb-4">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Owner</a></li>
      <li class="breadcrumb-item" aria-current="page"><a href="<%= owner_offers_path %>">Offers</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="<%= new_owner_offer_path %>"></a>Create Offer</li>
    </ol>
  </nav>

  <%= render "form", url: owner_offers_path, action: 'create' , method: :post %>
</div>