config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors, controllers: {
    sessions: 'visitors/sessions',
    registrations: 'visitors/registrations',
    passwords: 'visitors/passwords'
  }
  devise_for :users

  resources :offers, only: [:index] do
    member do
      get :select, :delete
    end
  end

  namespace :owner do
    resources :offers, only: %i[new create edit update destroy index]
  end

  root to: 'home#index'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :visitor, optional: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_visitor!

  def index
    @offers = Offer.where(visitor_id: [nil, current_visitor.id])
  end

  def select
    @offer = Offer.find_by_id(params[:id])

    if @offer&.update(visitor_id: current_visitor.id)
      flash[:message] = 'Offer selected successfully.'
    else
      flash[:message] = 'Offer could not be selected.'
    end

    redirect_to offers_path
  end

  def delete
    @offer = Offer.find_by_id(params[:id])

    if @offer&.update(visitor_id: nil)
      flash[:message] = 'Offer successfully deleted.'
    else
      flash[:message] = 'Offer could not be deleted.'
    end

    redirect_to offers_path
  end
end

app/controllers/owner/offers_controller.rb
class Owner::OffersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_offer, only: %i[edit update destroy]

  def index
    @offers = Offer.all
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = current_user.offers.build(offer_params)

    if @offer.save
      flash[:message] = 'Offer successfully created.'
      redirect_to owner_offers_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @offer.update(offer_params)
      flash[:message] = 'Offer successfully updated.'
      redirect_to owner_offers_path
    else
      render :edit
    end
  end

  def destroy
    if @offer.destroy
      flash[:message] = 'Offer successfully deleted.'
      redirect_to owner_offers_path
    else
      redirect_to owner_offer_path(@offer)
    end
  end

  private

  # def authenticate_owner
  #   redirect_to root_path unless current_user.is_owner
  # end

  def set_offer
    @offer = Offer.find params[:id]
  end

  def offer_params
    params.require(:offer).permit(:starts, :ends, :days, :capacity, :parking_price, :discount)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/index.html.erb
<div class="container pt-4 pb-4">

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Visitor</a></li>
      <li class="breadcrumb-item active" aria-current="page">Offers</li>
    </ol>
  </nav>

  <%= render "shared/flash" %>

  <div class="card shadow-lg border-0">
    <div class="card-body p-0">
      <table class="table">
        <thead class="thead-dark">
          <tr class='text-center'>
            <th scope="col">ID</th>
            <th scope="col">Starts</th>
            <th scope="col">Ends</th>
            <th scope="col">Duration</th>
            <th scope="col">Capacity</th>
            <th scope="col">Parking Price</th>
            <th scope="col">Discount</th>
            <th scope="col">Select</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>

        <tbody>
          <% @offers.each do |offer| %>
            <tr class='text-center'>
              <th scope="row"><%= offer.id %></th>
              <td><%= offer.starts %></td>
              <td><%= offer.ends %></td>
              <td><%= offer.days %></td>
              <td><%= offer.capacity %></td>
              <td><%= offer.parking_price %></td>
              <td><%= offer.discount %></td>
              <% if offer.visitor_id == current_visitor.id %>
                <td><span class='badge badge-success'>Selected</span></td>
              <% else %>
                <td><%= link_to "Select this Offer", select_offer_path(offer) %></td>
              <% end %>
              <% if offer.visitor_id == current_visitor.id %>
                <td><%= link_to "Delete this Offer", delete_offer_path(offer), class: 'delete-offer' %></td>
              <% else %>
                <td><span class='badge badge-secondary'>Not Selected</span></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>