config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors, controllers: {
    sessions: 'visitors/sessions',
    registrations: 'visitors/registrations',
    passwords: 'visitors/passwords'
  }
  devise_for :users

  resources :offers, only: [:index] do
    member do
      get :select, :delete
    end
  end

  namespace :owner do
    resources :offers, only: %i[new create edit update destroy index]
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingReservation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Parking Reservation System</a>
      <% if user_signed_in? %>
        <div class="form-inline my-2 my-lg-0">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
          <%= link_to "Deactivate", user_registration_path, method: :delete, class: 'nav-item nav-link' %>
        </div>
      <% elsif visitor_signed_in? %>
        <div class="form-inline my-2 my-lg-0">
          <%= link_to "Sign Out", destroy_visitor_session_path, method: :delete, class: 'nav-item nav-link' %>
          <%= link_to "Deactivate", visitor_registration_path, method: :delete, class: 'nav-item nav-link' %>
        </div>
      <% else %>
        <div class="form-inline my-2 my-lg-0">
          <%= link_to "Login - Visitor", new_visitor_session_path, class: 'btn btn-secondary ml-2' %>
          <%= link_to "Login - Owner", new_user_session_path, class: 'btn btn-secondary ml-2' %>
        </div>
      <% end %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>